# Generated by Django 5.1.2 on 2024-11-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='encrypted_phone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
