# Generated by Django 5.1.2 on 2024-10-31 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
